### ISSUE TITLE
error CS1502, CS1503

### ISSUE THREAD

**Issue by iakovosvo** [yasirkula/UnityAssetUsageDetector#1]
I get: error CS1502: The best overloaded method match for `UnityEditor.EditorGUILayout.Foldout(bool, string, UnityEngine.GUIStyle)' has some invalid arguments

and error CS1503: Argument `#3' cannot convert `bool' expression to type `UnityEngine.GUIStyle'

**Comment by yasirkula** [comment]
It is using this overload of the Foldout function:

public static bool Foldout(bool foldout, string content, bool toggleOnLabelClick, GUIStyle style = EditorStyles.foldout);

You can fix it by making the following change:

showSubAssetsFoldout = EditorGUILayout.Foldout( showSubAssetsFoldout, "Include sub-assets in search:" );

May I ask your Unity version, though?

**Comment by iakovosvo** [comment]
Thanks, works fine now. I am using 5.3.2
