### ISSUE TITLE
Search for References sometimes not searching the Sub-Assets

### ISSUE THREAD

**Issue by rotter** [yasirkula/UnityAssetUsageDetector#10]
I started using your plugin on a new project now.

I tried using Search for References context action on an image I knew was being used, and it gave me 0 results. Then I tried Search for References on that image's inner sprite/texture and it found some results.

Then as further test I used Search for References on the same image again with the same output (0 results). Then I clicked on Reset Search, ran the search on the window (GO!) and it worked (found some results). I can reproduce this error every time (Search for Reference on image -> 0 results, click Reset Search, click Go, find some results). So it seems the search window is not being properly initialized on some situations (or maybe always?) when using the Search for References context option.

**Comment by yasirkula** [comment]
I can't reproduce this issue on Unity 5.6. Here's what I'm doing:

![sprites](https://user-images.githubusercontent.com/10211608/62727679-a61bb980-ba22-11e9-9e04-a8a242ed4154.png)

I'm assigning either Toggle or Handle to Image and RawImage objects in my scene. Then, I right click Toggle and select Search for References. It finds the reference in the scene.

Should I do something else? On which Unity version are you testing the plugin?

**Comment by rotter** [comment]
It doesnt happen with all images for me. I am using Unity 2019.1.12f

But I found out another thing. For some images that does return some results when I run the "Search for References", if I reset the search and search again it finds MORE results when I do the search through the window.

An example:
First search (context menu):
![image](https://user-images.githubusercontent.com/918721/62743143-abbfd200-ba17-11e9-9378-0e02f4ad8908.png)

Second search (click Reset and GO):
![image](https://user-images.githubusercontent.com/918721/62743130-9c408900-ba17-11e9-890e-9eff561950e3.png)

It seems to always filter out the "Sprite" references on the first search, and when I Reset & GO it then shows the sprite. And in some cases, the only reference is to Sprite, so it doesnt show anything on the first run, then show some Sprite hits on the 2nd run.

Unfortunately I am traveling abroad tomorrow morning (and I still didnt even start packing), so I wont be able to run any more tests for the next ~12 days.

**Comment by yasirkula** [comment]
I'll definitely check it out. I've also noticed the duplicate `[Property: mainTexture]` lines, I'll check it out, too.

**Comment by yasirkula** [comment]
This will fix the issue you've reported as well as the duplicate `[Property: mainTexture]` issue: [AssetUsageDetector.zip](https://github.com/yasirkula/UnityAssetUsageDetector/files/3488126/AssetUsageDetector.zip). I'll update the repo soon.
