### ISSUE TITLE
Asset not found after rename (cache issue?)

### ISSUE THREAD

**Issue by rotter** [yasirkula/UnityAssetUsageDetector#11]
This is a minor issue, but just happened to me and is completely reproducible:

1) Search for any image that is being used (using Context menu or regular/old way)
2) Results will show up
3) Rename that image and repeat search
4) No results will be found

If you save the current scene, change scene, repeat the search many more times it wont work, it will return 0 results always after you renamed the image.

The only way I found to "fix" this was to rename the asset that uses the image (in my case a Prefab). I tried reimporting the image and reimporting the prefab and none worked. Maybe restarting Unity would fix also but I havent tried.

**Comment by yasirkula** [comment]
This is a serious issue. I was able to reproduce it and will see what I can do.

**Comment by yasirkula** [comment]
Resolved in https://github.com/yasirkula/UnityAssetUsageDetector/commit/0cd657456dc410f14c0e0ba2e752345c9f5d30fc.
