### ISSUE TITLE
No references found to sprite or sound asset

### ISSUE THREAD

**Issue by TimmermanV** [yasirkula/UnityAssetUsageDetector#12]
I have been using this UnityAssetUsageDetector for quite some time and it worked great until the large refactor/rewrite some time ago. Now I can´t seem to get it to work. This is what I´m trying.

I created a new project.  Added one image to the project and dragged it into the scene. 
Searched for that image using the Asset Usage Detector. Even though I'm searching "All scenes in the project", no results are found. Even when ticking all boxes in Search variables and search properties.
I also tried adding a wav file and dragging it into the scene hierarchy, creating an object with an AudioSource this way. Now I'm searching for this audio clip asset using Asset Usage Detector, but I'm not getting any results.  (I did save the scene btw)

I'm using Unity 2019.1.8f1.

Here's my project with example scene and (free) assets: [ExampleScene.zip](https://github.com/yasirkula/UnityAssetUsageDetector/files/3631836/ExampleScene.zip)

**Comment by yasirkula** [comment]
You're right, the current Asset Store version of the plugin fails to find a lot of references. I've already fixed the issue on the [GitHub version of the plugin](https://github.com/yasirkula/UnityAssetUsageDetector/blob/master/AssetUsageDetector.unitypackage), so you can import that to your project instead.

The GitHub version currently has issue #11 but I've fixed it on my local copy and will push an update in a short time. Then, I'll definitely update the Asset Store version of the plugin, too.

**Comment by yasirkula** [comment]
Resolved in https://github.com/yasirkula/UnityAssetUsageDetector/commit/0cd657456dc410f14c0e0ba2e752345c9f5d30fc.
