### ISSUE TITLE
AssetUsageDetector caused Unity to crash

### ISSUE THREAD

**Issue by TimmermanV** [yasirkula/UnityAssetUsageDetector#13]
I have updated to version 1.51. Now Unity seems to be consistently crashing when trying to search for references in all scenes in the project. I can't reproduce the crash on a smaller project (yet), so I'm not sure what's wrong. I attached the debug logs that contain the stack trace. It seems to be crashing in VariableGetter.cs:59. Any idea what might be wrong? Is there anything I could try or any additional information that would help diagnose the issue? (I'm using Unity 2019.1.8f1, .NET 4.x scripting runtime)
[error.log](https://github.com/yasirkula/UnityAssetUsageDetector/files/3639702/error.log)
[Editor.log](https://github.com/yasirkula/UnityAssetUsageDetector/files/3639703/Editor.log)

**Comment by yasirkula** [comment]
At **VariableGetter.cs:35** (inside the `public object Get( object obj )` function), can you insert the following line to see at which object the search is failing: `System.IO.File.AppendAllText( @"C:\Users\USERNAME\Documents\test.txt", "\n" + obj.GetType() + " " + name );`

**Comment by TimmermanV** [comment]
This change seems to be slowing down the search to a crawl. I ran it overnight for 9 hours and it didn't finish. (The log of the incomplete search log contains 57910 lines.) I just accidentally interrupted the search by trying to copy the output file which triggered an "ERROR: search was interrupted" error. I guess this happened since it was trying to write to this file while I was making a copy. So now I have to start over...   Is there any way I can make this faster?

**Comment by yasirkula** [comment]
Wow, thanks for the dedication! Please try to narrow down the search by first commenting out the AppendAllText line and then searching only in Assets folder, only in a particular scene, only in public variables, only in private properties and etc. until you narrow down the crashing case as much as you can. If crash occurs when searching the assets, try adding root folders in your Project to "Don't search following asset(s):" to exclude them from the search. This way, you may even be able to pinpoint the problematic asset itself! Then, you should uncomment the AppendAllText line and start the search.

**Comment by TimmermanV** [comment]
I tried narrowing down the problem and ended up with a single scene with one object (that does include a NodeCanvas behaviourtree, which may be the source of the issue). However, the search was still taking too long, so I added a counter and did a manual binary search to find the number of calls to that Get function before it would crash. (It was about 395394) Then I changed the code to only start logging the last couple of calls. Unfortunately that doesn´t seem to reveal that much, since the last line of output ("System.Reflection.MonoField ReflectedType") is also present many times in the first 65770 calls.
[AssetUsageDetectorLog_First_65770.txt](https://github.com/yasirkula/UnityAssetUsageDetector/files/3650926/AssetUsageDetectorLog_First_65770.txt)
[AssetUsageDetectorLog_Last_4.txt](https://github.com/yasirkula/UnityAssetUsageDetector/files/3650927/AssetUsageDetectorLog_Last_4.txt)

**Comment by yasirkula** [comment]
I think this is the same issue as #6, except that this issue wasn't exclusive to System.Assembly: System.Type and System.Reflection can be affected by this issue, as well.

Thankfully, there is an easy fix: simply change **Utilities.IsPrimitiveUnityType** as follows:

```csharp
public static bool IsPrimitiveUnityType( this Type type )
{
    return type.IsPrimitive || primitiveUnityTypes.Contains( type ) || type.IsEnum
        || typeof(Type).IsAssignableFrom(type) || type.Namespace == typeof(Assembly).Namespace;
}
```

**Comment by TimmermanV** [comment]
That seems to have fixed the crash. Thanks! Will you be releasing another version with this fix?

**Comment by yasirkula** [comment]
Yes, definitely. Very soon.
