### ISSUE TITLE
Callback during search to perform analysis or even refactoring

### ISSUE THREAD

**Issue by TimmermanV** [yasirkula/UnityAssetUsageDetector#14]
Would it be possible to use the search algorithm as the basis for automatic refactoring of assets, or gathering meta information / statistics? E.g. would it be possible to get a callback for each search result so I can run some code?

I have tried a couple of things, but the code lives in the Editor Assembly and doesn't seem to know about the MonoBehaviours that are in my project.

Thanks!

**Comment by yasirkula** [comment]
You can create a folder named **Standard Assets** at the root of your Assets folder and move the AssetUsageDetector folder there. Afterwards, you can access AssetUsageDetector from a MonoBehaviour. I'd recommend you to write your code inside a MonoBehaviour and wrap your code with `#if UNITY_EDITOR` and `#endif` directives.

In your function, you can create a new **AssetUsageDetector** instance, call its **Run** function and iterate over the elements of the resulting **SearchResult** data.

**Comment by yasirkula** [comment]
Alternatively, you can wrap all AssetUsageDetector classes with `#if UNITY_EDITOR` and `#endif` directives and then move all the scripts to the Assets folder to access AssetUsageDetector from regular classes.

**Comment by TimmermanV** [comment]
Thank you, I'll try those suggestions.
