### ISSUE TITLE
Scenes not found using SceneReference Object

### ISSUE THREAD

**Issue by ReVDiZ** [yasirkula/UnityAssetUsageDetector#22]
Hello !

First thanks for your AssetUsageDetector, it's really useful !

But I cannot find any references of a specific scene in my project, but i am 200% sure there is one.

I am using SceneReference Objects from JohannesMP : https://gist.github.com/JohannesMP/ec7d3f0bcf167dab3d0d3bb480e0e07b

Here is some pictures :
_YOUR TOOL_
![YourTool](https://user-images.githubusercontent.com/9308290/84777767-50b91d00-afe2-11ea-8836-b93faa5bb818.png)

_NORMAL INSPECTOR_
![Normal](https://user-images.githubusercontent.com/9308290/84777801-5c0c4880-afe2-11ea-867e-c964c921bede.png)

_DEBUG INSPECTOR_
![Debug](https://user-images.githubusercontent.com/9308290/84777836-64fd1a00-afe2-11ea-9b44-30f1d4f08774.png)

**Comment by yasirkula** [comment]
Scene assets were causing problems with AssetDatabase.LoadAllAssetsAtPath and I didn't think that one could reference a scene asset in their objects, so I simply skipped them. But this is a valid use-case. Looks like commenting out these 2 lines fixes the issue without causing problems with AssetDatabase.LoadAllAssetsAtPath:

https://github.com/yasirkula/UnityAssetUsageDetector/blob/7d24aa4939651de5ae26c1365a91a135e6e62287/Plugins/AssetUsageDetector/Editor/AssetUsageDetector.cs#L756-L757
