### ISSUE TITLE
Warning: CS0618: prefabAssetPath is obsolete

### ISSUE THREAD

**Issue by puschie286** [yasirkula/UnityAssetUsageDetector#24]
Hi, we getting 5 warnings with the following messsage:
warning CS0618: 'PrefabStage.prefabAssetPath' is obsolete: 'prefabAssetPath has been deprecated. Use assetPath instead.'
list of usage
- AssetUsageDetector.cs(221,78)
- AssetUsageDetector.cs(222,33)
- AssetUsageDetectorWindow.cs(659,72)
- Utilities.cs(237,91)
- Utilities.cs(246,91)
do you mind to update it or is it required for backward compatibility reason ?
we using Unity 2020.1+

**Comment by yasirkula** [comment]
Are you using the latest version? I've addressed this issue on this commit: https://github.com/yasirkula/UnityAssetUsageDetector/commit/68f1b2809e7b848a6247c305ade355ee209298aa

**Comment by puschie286** [comment]
hmm, we use version 1.7.7 that is newest in unity package manager - missed to check the github version/releases

**Comment by puschie286** [comment]
thanks for pointing it out - we will switch to git version instead of asset store package version

**Comment by yasirkula** [comment]
You need to update the asset manually when using Asset Store. This requirement is actually the same when using Package Manager with git: you'll need to delete this repo's `lock` from **Packages/manifest.json** to update the plugin because Unity locks git packages to a specific commit.

**Comment by puschie286** [comment]
the asset store seems to be far behind the github version - thought they have same version. after switching to the github version the warnings are gone. thanks

**Comment by yasirkula** [comment]
It is actually up-to-date: https://assetstore.unity.com/packages/tools/utilities/asset-usage-detector-112837#releases. I keep my plugins up-to-date or almost up-to-date on Asset Store. Perhaps some sort of misleading Asset Store cache is displaying wrong information in your case.
