### ISSUE TITLE
Assets referenced by polymorphism [SerializeReference] not found

### ISSUE THREAD

**Issue by Staarter** [yasirkula/UnityAssetUsageDetector#33]
**Description of the bug**

Assets that are referenced by polymorphism using the tag [SerializeReference] are not found by AUD.

**Reproduction steps**

- Create scripts using these class : 
```csharp
using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public class ContainerBase { }

[System.Serializable]
public class ContainerGO : ContainerBase
{
	public GameObject go;
}

[CreateAssetMenu(fileName ="AUD_SerializeReference", menuName = "AUD_SerializeReference")]
public class DebugAUD_SerializeReference : ScriptableObject
{
	[SerializeReference] public List<ContainerBase> test = new List<ContainerBase>();

	private void OnValidate()
	{
		// Add an empty element here: we cannot do it in inspector by default
		test.Add(new ContainerGO());
	}
}

[CreateAssetMenu(fileName ="AUD_Default", menuName = "AUD_Default")]
public class DebugAUD_Default : ScriptableObject
{
	public List<ContainerGO> test = new List<ContainerGO>();
}
```

- Create the two ScriptableObject 'AUD_Default' & 'AUD_SerializeReference'.
- Add a prefab gameObject into theses two 'test' fields.
- Try to search this prefab using the AUD window
- Only the ScriptableObject 'AUD_Default' will be found as using the prefab.

![image_2023-02-21_182622092](https://user-images.githubusercontent.com/9812442/220416775-836a6af3-8d46-4b74-b696-add4ee35c46a.png)

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2020.3.16
- Platform: Windows
- How did you download the plugin: Asset Store (the asset is up to date)

**Additional info**

I know that Unity have made changes about SerializeField in 2021 or 2022, the serialization can be changed, but I am using 2020..

**Comment by yasirkula** [comment]
Thank you for bringing this to my attention! I'll include the fix in the next release but in the meantime, you can apply the fix yourself by changing these lines: https://github.com/yasirkula/UnityAssetUsageDetector/blob/8072530c2cc666007d79f0a8aae038a4d2d26878/Plugins/AssetUsageDetector/Editor/AssetUsageDetectorSearchFunctions.cs#L1421-L1425

As follows:

```csharp
case SerializedPropertyType.ManagedReference:
	object managedReferenceValue = GetRawSerializedPropertyValue( iterator );
	propertyValue = managedReferenceValue as Object;
	searchResult = SearchObject( PreferablyGameObject( managedReferenceValue ) );
	enterChildren = false;
	break;
```

**Comment by Staarter** [comment]
Thank you for your reply!
This fix works like a charm, good job.

**Comment by alijaya** [comment]
Hey, I don't know if I should start new issues or not. But I want to ask, according to the previous example. Is it possible to search by the class name? For example ContainerBase will give both result.

Because my game using heavy on Polymorphism, and I want to see what objects that use certain class.

**Comment by yasirkula** [comment]
https://github.com/yasirkula/UnityAssetUsageDetector/blob/8072530c2cc666007d79f0a8aae038a4d2d26878/Plugins/AssetUsageDetector/Editor/AssetUsageDetectorCache.cs#L50

This line is the same as right clicking an asset and selecting Select Dependencies. This is the key optimization technique Asset Usage Detector uses but it unfortunately doesn't work with ContainerBase script. To achieve what you want, you'd need to search every asset and scene in detail which would be much slower than current implementation.

**Comment by alijaya** [comment]
I see. Could you give me some directioin how to achieve this? I don't mind if it's being slow. I want to refactor some class, and I want to make sure all instance of its usage has been handled.

**Comment by yasirkula** [comment]
The first step is always returning `true` in this function: https://github.com/yasirkula/UnityAssetUsageDetector/blob/8072530c2cc666007d79f0a8aae038a4d2d26878/Plugins/AssetUsageDetector/Editor/AssetUsageDetector.cs#L1107

Now I expect every single object in your project to pass through this function (you might want to verify it first by logging `referenceNode.nodeObject` in an almost empty project): https://github.com/yasirkula/UnityAssetUsageDetector/blob/8072530c2cc666007d79f0a8aae038a4d2d26878/Plugins/AssetUsageDetector/Editor/AssetUsageDetectorSearchFunctions.cs#L1369

At this point, I'm not 100% certain about which path to follow either. But I know that SerializeReference objects pass through here: https://github.com/yasirkula/UnityAssetUsageDetector/blob/790a508dcd45526e338e06b771026b875f9f04a0/Plugins/AssetUsageDetector/Editor/AssetUsageDetectorSearchFunctions.cs#L1422

If your Type's instances are nested inside another Type that is stored with SerializeReference, I'm guessing that the nested variable will be iterated here (first [SearchObject](https://github.com/yasirkula/UnityAssetUsageDetector/blob/790a508dcd45526e338e06b771026b875f9f04a0/Plugins/AssetUsageDetector/Editor/AssetUsageDetectorSearchFunctions.cs#L1425) will be called and then this function): https://github.com/yasirkula/UnityAssetUsageDetector/blob/790a508dcd45526e338e06b771026b875f9f04a0/Plugins/AssetUsageDetector/Editor/AssetUsageDetectorSearchFunctions.cs#L1500

For SerializeField references, code will enter here instead: https://github.com/yasirkula/UnityAssetUsageDetector/blob/790a508dcd45526e338e06b771026b875f9f04a0/Plugins/AssetUsageDetector/Editor/AssetUsageDetectorSearchFunctions.cs#L1428

Here, you have access to `iterator.type` but it's a string. I think you can use `fieldInfoGetter(iterator, out Type actualType)` but it might be null under unknown circumstances. It's an internal Unity API.

You can also fallback to reflection approach by changing this line to `if (forceUseSerializedObject)`: https://github.com/yasirkula/UnityAssetUsageDetector/blob/790a508dcd45526e338e06b771026b875f9f04a0/Plugins/AssetUsageDetector/Editor/AssetUsageDetectorSearchFunctions.cs#L1375

Now 'almost' every call will fallback to `SearchVariablesWithReflection`. At this point you have easy access to iterated objects' Types. But I'm unsure if reflection approach enters variables with SerializeReference attribute. You need to test it first.

**Comment by yasirkula** [comment]
You can call `AssetDatabase.FindAssets("t:MonoScript");` and store the MonoScript->Type mappings in a static Dictionary. Then reuse that Dictionary if not null.

**Comment by alijaya** [comment]
Yes that would be a good idea, thanks for the insight :D

**Comment by alijaya** [comment]
Hi @yasirkula , I'm stumped, because sometimes my solution works and sometimes it doesn't work. I have a ScriptableObject that has SerializeReference inside, when I search for the script, it doesn't show. But when I duplicate the ScriptableObject, it finds the duplicated one, but not the original one. What happens? Is it because of caching? How to delete the cache?

**Comment by yasirkula** [comment]
You can delete the cache from `Library/AssetUsageDetector.cache` but make sure to close all Asset Usage Detector windows beforehand. If possible, can you create a Unitypackage from the broken ScriptableObject and its referenced object and send it to me along with the broken cache file (either from here or via [email](mailto:yasirkula@gmail.com)) so that I can reproduce the issue and see if it can somehow be fixed?

Please let me know if deleting the cache works.
