### ISSUE TITLE
Feature request: found asset name in the search list

### ISSUE THREAD

**Issue by iMobCoding** [yasirkula/UnityAssetUsageDetector#35]
Right now I have to click the item in the search list to see which project assets it belongs to. 
Possible to display that asset name in the search list?  Maybe someone wouldn't like that, so maybe an option in the Search dialog?

Thanks

![image](https://github.com/yasirkula/UnityAssetUsageDetector/assets/1320690/8d6c0f72-6c22-40a1-bf7b-b6fc8049018b)

**Comment by iMobCoding** [comment]
Thanks. I will try and let you know...

**Comment by yasirkula** [comment]
Even better, I've added a setting to the plugin's Settings menu just like you've asked.

**Comment by iMobCoding** [comment]
It works perfectly. Thank you very much :)
