### ISSUE TITLE
Unused Objects tab displays objects that are being used. 

### ISSUE THREAD

**Issue by Shamsad-Madovergames** [yasirkula/UnityAssetUsageDetector#39]
The main issue i faced for the sprites. it takes sprites as two components sprite and texture. if a particle effect is using a sprites texture it will still show the sprite in the unused asset. i have deleted a lots of sprites and then had to revert them back. please fix this issue. if the object is used in anyway then please don't show it in the unused asset tab.
![image](https://github.com/yasirkula/UnityAssetUsageDetector/assets/125637874/bd77dee3-6005-4b0a-9261-9ca9fbd40242)
![image](https://github.com/yasirkula/UnityAssetUsageDetector/assets/125637874/2ae7ee5b-9e13-4027-a047-e7375ba7f737)

**Comment by yasirkula** [comment]
I will make it optional badd an option to Settings for this (optional behaviour).
