### ISSUE TITLE
CS0618 UnityAssetUsageDetector uses functionality that is obsolete in Unity 2018.3 (Prefab/GUI)

### ISSUE THREAD

**Issue by TimmermanV** [yasirkula/UnityAssetUsageDetector#4]
Assets/Plugins/AssetUsageDetector/Editor/AssetUsageDetector.cs(1931,47): warning CS0618: `UnityEditor.PrefabUtility.GetPrefabParent(UnityEngine.Object)' is obsolete: `Use GetCorrespondingObjectFromSource.'

Assets/Plugins/AssetUsageDetector/Editor/AssetUsageDetector.cs(1932,71): warning CS0618: `UnityEditor.PrefabUtility.FindRootGameObjectWithSameParentPrefab(UnityEngine.GameObject)' is obsolete: `FindRootGameObjectWithSameParentPrefab is deprecated, please use GetOutermostPrefabInstanceRoot instead.'

Assets/Plugins/AssetUsageDetector/Editor/AssetUsageDetector.cs(2178,85): warning CS0618: `UnityEngine.GUIText' is obsolete: `This component is part of the legacy UI system and will be removed in a future release.'

**Comment by yasirkula** [comment]
Fixed: https://github.com/yasirkula/UnityAssetUsageDetector/commit/93b8b267eb23f7c10b7f8ab7a7308fc688166a95
