### ISSUE TITLE
Using GUILayout.XScope

### ISSUE THREAD

**Issue by bazuka5801** [yasirkula/UnityAssetUsageDetector#5]
Hello, why you didn't used GUILayout.XScope with using statement? This is simplify our life to read the code)
https://docs.unity3d.com/ScriptReference/GUILayout.HorizontalScope.html
https://docs.unity3d.com/ScriptReference/GUILayout.VerticalScope.html

**Comment by yasirkula** [comment]
I didn't know about these functions, to be honest. Regardless, I think using GUILayout.BeginHorizontal and GUILayout.EndHorizontal would be more performant than using HorizontalScope because using a "using" statement would result in an additional Dispose function call.
