### ISSUE TITLE
Black font color is hard to read

### ISSUE THREAD

**Issue by rotter** [yasirkula/UnityAssetUsageDetector#7]
Thanks for another great plugin, I'm your fan, use a lot of your plugins :)

On the "Asset Usage Detector" window some texts are in black font color, and for me (I use the Dark theme) it's almost impossible to read. Maybe detect the theme and change the font color? Or just use a more standard color such as white?

Examples of elements that I cant read:
"Don't forget..." (I honestly cant read the rest)
"No results found"

Some other disabled elements are hard to read but possible, such as "Asset(s)" once a search is completed.

I have attached a screenshot but I dont know if the visibility will be the same on your computer (maybe your monitor has a higher brightness etc), but believe me, on my computer it's almost impossible to read. Everything else on Unity is pretty easy to read (almost all elements use white font).

![image](https://user-images.githubusercontent.com/918721/62383707-c29d8a80-b526-11e9-95ac-3a310cf8a0da.png)

**Comment by yasirkula** [comment]
Will see what I can do. Thanks for reporting this.

**Comment by yasirkula** [comment]
Can you see if these issues are gone in https://github.com/yasirkula/UnityAssetUsageDetector/commit/3cea7a93e729684332f301e67f5b4e3407275b6b?

**Comment by rotter** [comment]
Now it's perfect, thanks a lot!

![image](https://user-images.githubusercontent.com/918721/62424855-07eac500-b6ab-11e9-9998-6068f00ce66a.png)
