### ISSUE TITLE
Suggestion: context menu on right click

### ISSUE THREAD

**Issue by rotter** [yasirkula/UnityAssetUsageDetector#8]
I liked this plugin, it's helping me find duplicate and unused images on my game, but I find it a bit cumbersome to drag the files I want to search to the search window (and before doing that I have to [Reset] and then [-] to remove the previous file and then drag).

If there was a context menu integration where I could right-click on the file I want to search and it would put that file as the single asset of the search and perform the search it would be awesome.

The context menu part is pretty easy, but I dont know the part of showing your window, resetting the current search, removing the assets, adding this asset to the search and starting the search

```
[MenuItem("Assets/Run Asset Usage Detector")]
private static void PerformAssetUsageSearch()
{
       Debug.Log("Do something with the Selection: " + Selection.activeObject.name);
}
```

**Comment by yasirkula** [comment]
Good idea. Thanks for the suggestion!

**Comment by yasirkula** [comment]
Added **Search For References** context menu item in https://github.com/yasirkula/UnityAssetUsageDetector/commit/3cea7a93e729684332f301e67f5b4e3407275b6b. Also added `AssetUsageDetectorWindow.ShowAndSearch` function to quickly initiate a search with custom parameters from an editor script.

**Comment by rotter** [comment]
Working great, thanks!!
