### ISSUE TITLE
Suggestion: use the Releases on Github so we can watch

### ISSUE THREAD

**Issue by rotter** [yasirkula/UnityAssetUsageDetector#9]
Adding the releases under Releases tab/feature on Github allows us to get notified when a new version is released, which is very helpful (for me at least).

**Comment by yasirkula** [comment]
Out of curiosity, doesn't **Watch** also have the same effect?

**Comment by rotter** [comment]
There are different Watch levels. I never use the complete Watch because Im afraid I will get spammed by several emails/notifications (especially on large repos), so I always only use "Watch Releases", because usually that's all what Im interested in (unless Im part of the dev team of that repo or something).

![image](https://user-images.githubusercontent.com/918721/62424790-269c8c00-b6aa-11e9-959f-1cc9dc82db32.png)

**Comment by yasirkula** [comment]
I see. I am not used to creating releases via _Releases_ but I definitely hear you. Let me think about using the _Releases_ page.
